version: '3'

services:

  mumble:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhilker/murmur
    volumes:
      - data:/var/lib/murmur/:rw
      - ${MUMBLE_TLS_CERT}:/etc/murmur/certs/fullchain.pem:ro
      - ${MUMBLE_TLS_KEY}:/etc/murmur/certs/privkey.pem:ro
    ports:
      - 64738:64738
      - 64738:64738/udp
    restart: unless-stopped

volumes:
  data:
