version: '3.7'

services:

  mumble:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhilker/murmur
    volumes:
      - data:/var/lib/murmur/:rw
      - ${MUMBLE_TLS_CERT}:/etc/murmur/fullchain.pem:ro
      - ${MUMBLE_TLS_KEY}:/etc/murmur/privkey.pem:ro
    ports:
      - 6502:6502
      - 64738:64738
      - 64738:64738/udp

volumes:
  data:
