version: '3'

services:

  mumble:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhilker/murmur
    volumes:
      - data:/var/lib/murmur/:rw
      - /root/certs:/etc/murmur/certs/:ro
    ports:
      - 64738:64738
      - 64738:64738/udp
    environment:
      - TLS_CERT_FILE=mumble.darkgenesis.de.crt
      - TLS_KEY_FILE=mumble.darkgenesis.de.key
      - VIRTUAL_HOST=mumble.darkgenesis.de
      - LETSENCRYPT_HOST=mumble.darkgenesis.de
      - LETSENCRYPT_EMAIL=maikhilker89@gmail.com
    restart: unless-stopped
    networks:
      - nginx-proxy

volumes:
  data:
networks:
  nginx-proxy:
    external:
      name: "nginx-proxy"
