version: '3'

services:

  mumble:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhilker/murmur
    volumes:
      - ./data/:/var/lib/murmur/
    ports:
      - 64738:64738
      - 64738:64738/udp
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
