version: '3'

services:

  mumble:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhilker/murmur
    volumes:
      - ./data/:/var/lib/murmur/
      - ./fullchain.pem:/etc/murmur/fullchain.pem
      - ./privkey.pem:/etc/murmur/privkey.pem
    ports:
      - 64738:64738
      - 64738:64738/udp
